### ISSUE TITLE
Property types validation

### ISSUE THREAD

**Issue by feymartynov** [netology-group/mqtt-gateway#38]
When an MQTT v3.* client sends a message and the broker delivers it to an MQTT v5 client it would crash if the first client specifies a value of invalid type. E.g. all user-properties must be UTF-8 strings but someone may specify an integer in JSON. So anyone can crash the whole broker that way causing restart and reconnection of all the clients.

**Comment by alexkonst** [comment]
Also we need to move `status` field from 'properties' to `userProperties`and change type from number to string? (for `subscription.create` and `subscription.delete` requests)
https://github.com/netology-group/mqtt-gateway/blob/master/src/mqttgw.erl#L378-L380

**Comment by manifest** [comment]
Just changing the type to string (`<<"200">>`) will be enough.

**Comment by alexkonst** [comment]
One more question: do we need to support both v3 and v5 in mqtt-gateway plugin?

**Comment by feymartynov** [comment]
Yes until we have v3 clients. All services using svc-agent use v3 because there's no good pure Rust v5 client implementation yet.

**Comment by manifest** [comment]
It has been solved in the [PR](https://github.com/netology-group/mqtt-gateway/pull/40).
