### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by uwejan** [netology-group/mqtt-gateway#69]
Hi, am already using webhooks, which is more than fine, in my case.
The thing is i have to use classical username and password.
Will this plugin save me that by passing only a token as username?
another how to, how do i install this plugin on an already configured vernemq node.
Many thanks.

**Comment by manifest** [comment]
Hey  uwejan,

I'm not sure if I get you correctly, but if you will run this [example](https://github.com/netology-group/mqtt-gateway#authentication-using-json-web-tokens) with these environment variables set
```
APP_AUTHN_ENABLED=1
APP_AUTHZ_ENABLED=0
APP_DYNSUB_ENABLED=0
APP_STAT_ENABLED=0
```
you will get an `agent_id` property within each published message. The `agent_id` is basically `aud` + `sub` from the JWT passed as a password.

I hope this helps.

**Comment by manifest** [comment]
Hey @uwejan,
